POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1cGVydXNlciIsImlkIjoiNjVmOWNjNzUxMDdjOThjNGRjYmVmY2JjIiwiaWF0IjoxNzEwOTYyOTI2fQ.zo9iHY6V_ZeGt3B3AIkvotcm9K4KGLuTrQ3g5Juq4Jg


{
    "title": "TestBlog55555",
    "author": "Matti Mannila",
    "url": "nonexistent",
    "likes": 0,
    "userId": "65f9cc75107c98c4dcbefcbc"
}